import Head from "next/head";
import { useAuth } from "@/firebase/authFunctions";
import LogIn from "./posts/auth/logIn";
import Top from "@/pages/posts/Top"

export default function Home() {
  const currentUser = useAuth();
  return (
    <>
      <Head>
        <title>Sport Matching App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {currentUser !== null ? <LogIn /> : <Top />}
      {/* <LogIn /> */}
      {/* <Top /> */}
    </>
  );
}
