import Head from "next/head";
import Top from "@/pages/posts/Top";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sport Matching App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Top />
    </>
  );
}
